import type { WorkflowEdge, WorkflowNode, WorkflowVariable } from '../shared/types'

export interface SeedNode {
  id: string
  type: WorkflowNode['type']
  name: string
  x: number
  y: number
  agent?: string | undefined
  agentFlags?: string | undefined
  prompt?: string | undefined
  message?: string | undefined
  command?: string | undefined
  _roleName?: string | undefined
  // base fields
  continueOnError?: boolean | undefined
  timeout?: number | undefined
  retryCount?: number | undefined
  retryDelayMs?: number | undefined
  // agent
  skillId?: string | undefined
  permission?: 'read' | 'edit' | 'full' | undefined
  // condition
  conditionMode?: 'exitCode' | 'outputMatch' | undefined
  conditionPattern?: string | undefined
}

export interface SeedWorkflowBlueprint {
  id: string
  name: string
  description: string
  nodes: SeedNode[]
  edges: WorkflowEdge[]
  variables?: WorkflowVariable[] | undefined
}

export const SEED_WORKFLOWS: SeedWorkflowBlueprint[] = [
  {
    id: 'seed-wf-bug-fix',
    name: 'Autonomous Bug Fix',
    description: 'Reproduce a bug, write a failing test, then loop fix→test until green.',
    nodes: [
      {
        id: 'repro',
        type: 'agent',
        name: 'Reproduce',
        x: 0,
        y: 0,
        agent: 'claude-code',
        continueOnError: true,
        timeout: 300000,
        prompt:
          'Goal: reproduce the bug {{BUG_DESC}} in {{TARGET_PATH}}.\nConstraints: do NOT fix anything yet.\nDone when: you can state exact reproduction steps.\nEnd with a ## SUMMARY of the repro steps.',
      },
      {
        id: 'write_test',
        type: 'agent',
        name: 'Write failing test',
        x: 220,
        y: 0,
        agent: 'claude-code',
        _roleName: 'Tester',
        retryCount: 1,
        timeout: 300000,
        prompt:
          'Goal: add a failing automated test that captures the bug.\nConstraints: it must fail for the right reason; do not touch production code.\nDone when: the new test exists and fails.\nEnd with a ## SUMMARY (test file + name).',
      },
      {
        id: 'fix',
        type: 'agent',
        name: 'Fix root cause',
        x: 440,
        y: 0,
        agent: 'codex',
        _roleName: 'Developer',
        retryCount: 1,
        timeout: 600000,
        prompt:
          'Goal: fix the root cause so the failing test passes (use the context).\nConstraints: do not weaken or delete the test; minimal change.\nDone when: the fix is applied.\nEnd with a ## SUMMARY (what changed and why).',
      },
      {
        id: 'run_tests',
        type: 'shell',
        name: 'Run tests',
        x: 660,
        y: 0,
        command: '{{TEST_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'cond_pass',
        type: 'condition',
        name: 'Tests pass?',
        x: 880,
        y: 0,
        conditionMode: 'exitCode',
      },
      {
        id: 'commit',
        type: 'checkpoint',
        name: 'Review & commit',
        x: 1100,
        y: 0,
        message: 'Tests pass. Review the diff, then commit.',
      },
      {
        id: 'escape_fix',
        type: 'checkpoint',
        name: 'Did not converge',
        x: 880,
        y: 160,
        message: 'Tests still failing after 5 fix attempts — review state.',
      },
    ],
    edges: [
      { id: 'e1', fromNodeId: 'repro', toNodeId: 'write_test' },
      { id: 'e2', fromNodeId: 'write_test', toNodeId: 'fix' },
      { id: 'e3', fromNodeId: 'fix', toNodeId: 'run_tests' },
      { id: 'e4', fromNodeId: 'run_tests', toNodeId: 'cond_pass' },
      { id: 'e5', fromNodeId: 'cond_pass', toNodeId: 'commit', branch: 'true' },
      {
        id: 'e6',
        fromNodeId: 'cond_pass',
        toNodeId: 'fix',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 5,
      },
      { id: 'e7', fromNodeId: 'cond_pass', toNodeId: 'escape_fix', branch: 'false' },
    ],
    variables: [
      { name: 'BUG_DESC', label: 'Describe the bug', type: 'text', required: true },
      { name: 'TARGET_PATH', label: 'Focus path', type: 'path' },
      { name: 'TEST_CMD', label: 'Test command', type: 'string', default: 'npm test' },
    ],
  },
  {
    id: 'seed-wf-feature-pipeline',
    name: 'Feature Pipeline',
    description:
      'Gated cross-agent pipeline: plan (Architect) → approve → build (Codex) → review → tests, with dual recovery loops back to build and a final ship gate.',
    nodes: [
      {
        id: 'plan',
        type: 'agent',
        name: 'Plan feature',
        x: 0,
        y: 0,
        agent: 'claude-code',
        _roleName: 'Architect',
        timeout: 300000,
        prompt:
          'Goal: produce an implementation plan for {{FEATURE_DESC}} in {{TARGET_PATH}}.\nConstraints: list files to change, approach, and risks; no code yet.\nDone when: plan is complete.\nEnd with a ## SUMMARY (numbered plan).',
      },
      {
        id: 'approve_plan',
        type: 'checkpoint',
        name: 'Approve plan',
        x: 220,
        y: 0,
        message: 'Review the implementation plan before building.',
      },
      {
        id: 'build',
        type: 'agent',
        name: 'Build feature',
        x: 440,
        y: 0,
        agent: 'codex',
        _roleName: 'Developer',
        retryCount: 1,
        timeout: 600000,
        prompt:
          'Goal: implement the approved plan (in context).\nConstraints: stay within the plan scope; follow existing patterns.\nDone when: implemented.\nEnd with a ## SUMMARY (files changed and how).',
      },
      {
        id: 'review',
        type: 'agent',
        name: 'Review implementation',
        x: 660,
        y: 0,
        agent: 'claude-code',
        _roleName: 'Reviewer',
        timeout: 300000,
        prompt:
          'Goal: review the implementation for correctness, bugs, and convention adherence.\nConstraints: be specific (file:line); check against the plan in context.\nDone when: reviewed.\nEnd with a ## SUMMARY and a final line REVIEW_PASS or REVIEW_FAIL: <reasons>.',
      },
      {
        id: 'cond_review',
        type: 'condition',
        name: 'Review passed?',
        x: 880,
        y: 0,
        conditionMode: 'outputMatch',
        conditionPattern: 'REVIEW_PASS',
      },
      {
        id: 'run_tests',
        type: 'shell',
        name: 'Run tests',
        x: 1100,
        y: 0,
        command: '{{TEST_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'cond_tests',
        type: 'condition',
        name: 'Tests green?',
        x: 1320,
        y: 0,
        conditionMode: 'exitCode',
      },
      {
        id: 'ship',
        type: 'checkpoint',
        name: 'Ship',
        x: 1540,
        y: 0,
        message: 'Feature complete, review clean, tests green. Ship?',
      },
      {
        id: 'escape_build',
        type: 'checkpoint',
        name: 'Did not converge',
        x: 880,
        y: 220,
        message: "Build didn't pass review/tests after 4 attempts — review.",
      },
    ],
    edges: [
      { id: 'fp_e1', fromNodeId: 'plan', toNodeId: 'approve_plan' },
      { id: 'fp_e2', fromNodeId: 'approve_plan', toNodeId: 'build' },
      { id: 'fp_e3', fromNodeId: 'build', toNodeId: 'review' },
      { id: 'fp_e4', fromNodeId: 'review', toNodeId: 'cond_review' },
      { id: 'fp_e5', fromNodeId: 'cond_review', toNodeId: 'run_tests', branch: 'true' },
      {
        id: 'fp_e6',
        fromNodeId: 'cond_review',
        toNodeId: 'build',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 4,
      },
      { id: 'fp_e7', fromNodeId: 'cond_review', toNodeId: 'escape_build', branch: 'false' },
      { id: 'fp_e8', fromNodeId: 'run_tests', toNodeId: 'cond_tests' },
      { id: 'fp_e9', fromNodeId: 'cond_tests', toNodeId: 'ship', branch: 'true' },
      {
        id: 'fp_e10',
        fromNodeId: 'cond_tests',
        toNodeId: 'build',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 4,
      },
      { id: 'fp_e11', fromNodeId: 'cond_tests', toNodeId: 'escape_build', branch: 'false' },
    ],
    variables: [
      { name: 'FEATURE_DESC', label: 'Feature description', type: 'text', required: true },
      { name: 'TARGET_PATH', label: 'Target path', type: 'path' },
      { name: 'TEST_CMD', label: 'Test command', type: 'string', default: 'npm test' },
    ],
  },
  {
    id: 'seed-wf-parallel-review',
    name: 'Parallel Deep Review',
    description:
      'Fans four reviewers (bugs, security, perf, types) out concurrently from a scope step, joins them into a synthesis, then gates before a Codex fix and re-test.',
    nodes: [
      {
        id: 'scope',
        type: 'shell',
        name: 'Scope codebase',
        x: 0,
        y: 0,
        command:
          'if [ "{{DIFF_ONLY}}" = "no" ]; then git -C {{TARGET_PATH}} ls-files; else git -C {{TARGET_PATH}} diff HEAD; fi',
        continueOnError: true,
        timeout: 60000,
      },
      {
        id: 'rev_bugs',
        type: 'agent',
        name: 'Review: bugs',
        x: 220,
        y: -330,
        agent: 'claude-code',
        _roleName: 'Reviewer',
        timeout: 300000,
        prompt:
          'Goal: review the scoped code (in context) for correctness and logic bugs.\nConstraints: be specific — cite file:line for every finding.\nDone when: reviewed.\nEnd with a ## SUMMARY: findings as "file:line — severity — issue", ≤ 2.5 KB.',
      },
      {
        id: 'rev_security',
        type: 'agent',
        name: 'Review: security',
        x: 220,
        y: -110,
        agent: 'claude-code',
        _roleName: 'Security Auditor',
        timeout: 300000,
        prompt:
          'Goal: review the scoped code (in context) for security vulnerabilities — injection, path traversal, secret handling, unsafe IPC.\nConstraints: be specific — cite file:line for every finding.\nDone when: reviewed.\nEnd with a ## SUMMARY: findings as "file:line — severity — issue", ≤ 2.5 KB.',
      },
      {
        id: 'rev_perf',
        type: 'agent',
        name: 'Review: performance',
        x: 220,
        y: 110,
        agent: 'claude-code',
        _roleName: 'Reviewer',
        timeout: 300000,
        prompt:
          'Goal: review the scoped code (in context) for performance issues — hot loops, N+1 queries, memory leaks, unnecessary work.\nConstraints: be specific — cite file:line for every finding.\nDone when: reviewed.\nEnd with a ## SUMMARY: findings as "file:line — severity — issue", ≤ 2.5 KB.',
      },
      {
        id: 'rev_types',
        type: 'agent',
        name: 'Review: types',
        x: 220,
        y: 330,
        agent: 'claude-code',
        _roleName: 'Reviewer',
        timeout: 300000,
        prompt:
          'Goal: review the scoped code (in context) for type-safety issues and API/interface design problems.\nConstraints: be specific — cite file:line for every finding.\nDone when: reviewed.\nEnd with a ## SUMMARY: findings as "file:line — severity — issue", ≤ 2.5 KB.',
      },
      {
        id: 'synthesize',
        type: 'agent',
        name: 'Synthesize findings',
        x: 440,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: merge the four review summaries from context (labelled by node: rev_bugs, rev_security, rev_perf, rev_types).\nConstraints: deduplicate overlapping findings, rank by severity, drop noise.\nDone when: a unified prioritized list is produced.\nEnd with a ## SUMMARY: prioritized fix list.',
      },
      {
        id: 'approve_fixes',
        type: 'checkpoint',
        name: 'Approve fixes',
        x: 660,
        y: 0,
        message: 'Review prioritized findings; approve which to fix.',
      },
      {
        id: 'fix',
        type: 'agent',
        name: 'Apply fixes',
        x: 880,
        y: 0,
        agent: 'codex',
        _roleName: 'Developer',
        retryCount: 1,
        timeout: 600000,
        prompt:
          'Goal: fix the approved findings (in context).\nConstraints: minimal, scoped changes; do not expand scope beyond approved findings.\nDone when: applied.\nEnd with a ## SUMMARY (what was fixed).',
      },
      {
        id: 'retest',
        type: 'shell',
        name: 'Re-test',
        x: 1100,
        y: 0,
        command: '{{TEST_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
    ],
    edges: [
      { id: 'pr_e1', fromNodeId: 'scope', toNodeId: 'rev_bugs' },
      { id: 'pr_e2', fromNodeId: 'scope', toNodeId: 'rev_security' },
      { id: 'pr_e3', fromNodeId: 'scope', toNodeId: 'rev_perf' },
      { id: 'pr_e4', fromNodeId: 'scope', toNodeId: 'rev_types' },
      { id: 'pr_e5', fromNodeId: 'rev_bugs', toNodeId: 'synthesize' },
      { id: 'pr_e6', fromNodeId: 'rev_security', toNodeId: 'synthesize' },
      { id: 'pr_e7', fromNodeId: 'rev_perf', toNodeId: 'synthesize' },
      { id: 'pr_e8', fromNodeId: 'rev_types', toNodeId: 'synthesize' },
      { id: 'pr_e9', fromNodeId: 'synthesize', toNodeId: 'approve_fixes' },
      { id: 'pr_e10', fromNodeId: 'approve_fixes', toNodeId: 'fix' },
      { id: 'pr_e11', fromNodeId: 'fix', toNodeId: 'retest' },
    ],
    variables: [
      { name: 'TARGET_PATH', label: 'Target path', type: 'path', required: true },
      {
        name: 'DIFF_ONLY',
        label: 'Scope',
        type: 'choice',
        choices: ['yes', 'no'],
        default: 'yes',
      },
      { name: 'TEST_CMD', label: 'Test command', type: 'string', default: 'npm test' },
    ],
  },
  {
    id: 'seed-wf-coverage-loop',
    name: 'Coverage Loop',
    description:
      'Unattended metric loop: find gaps → write tests → run coverage with a line threshold, looping until the threshold passes (exit 0) or escaping after five rounds.',
    nodes: [
      {
        id: 'analyze_gaps',
        type: 'agent',
        name: 'Analyze gaps',
        x: 0,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: identify the most valuable untested code paths in {{TARGET_PATH}}.\nConstraints: prefer high-risk / low-coverage areas; on re-entry, target gaps not yet covered (re-derive coverage state by inspecting the code or the on-disk coverage report — the loop-back edge arrives from the condition, not the coverage shell, so the report is not in context).\nDone when: ranked gaps listed.\nEnd with a ## SUMMARY: top gaps.',
      },
      {
        id: 'write_tests',
        type: 'agent',
        name: 'Write tests',
        x: 220,
        y: 0,
        agent: 'codex',
        _roleName: 'Tester',
        retryCount: 1,
        timeout: 600000,
        prompt:
          'Goal: write tests for the top gaps identified in context.\nConstraints: do NOT modify production code; follow existing test patterns in the project.\nDone when: tests added.\nEnd with a ## SUMMARY (test files and what they cover).',
      },
      {
        id: 'coverage',
        type: 'shell',
        name: 'Run coverage',
        x: 440,
        y: 0,
        command: '{{COVERAGE_CMD}} --coverage.thresholds.lines={{COVERAGE_TARGET}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'cond_target',
        type: 'condition',
        name: 'Target met?',
        x: 660,
        y: 0,
        conditionMode: 'exitCode',
      },
      {
        id: 'done_cov',
        type: 'shell',
        name: 'Target reached',
        x: 880,
        y: 0,
        command: 'true',
      },
      {
        id: 'escape_cov',
        type: 'checkpoint',
        name: 'Did not converge',
        x: 660,
        y: 220,
        message: 'Coverage target not reached after 5 passes — review.',
      },
    ],
    edges: [
      { id: 'cl_e1', fromNodeId: 'analyze_gaps', toNodeId: 'write_tests' },
      { id: 'cl_e2', fromNodeId: 'write_tests', toNodeId: 'coverage' },
      { id: 'cl_e3', fromNodeId: 'coverage', toNodeId: 'cond_target' },
      { id: 'cl_e4', fromNodeId: 'cond_target', toNodeId: 'done_cov', branch: 'true' },
      {
        id: 'cl_e5',
        fromNodeId: 'cond_target',
        toNodeId: 'analyze_gaps',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 5,
      },
      { id: 'cl_e6', fromNodeId: 'cond_target', toNodeId: 'escape_cov', branch: 'false' },
    ],
    variables: [
      { name: 'TARGET_PATH', label: 'Target path', type: 'path' },
      { name: 'COVERAGE_TARGET', label: 'Line coverage target (%)', type: 'string', default: '80' },
      {
        name: 'COVERAGE_CMD',
        label: 'Coverage command',
        type: 'string',
        default: 'npm run test:coverage',
      },
    ],
  },
  {
    id: 'seed-wf-refactor-campaign',
    name: 'Refactor Campaign',
    description:
      'Analyze refactor scope, branch on risk (large scope routes through an approval gate), then loop refactor→test until green or escape after three attempts.',
    nodes: [
      {
        id: 'analyze',
        type: 'agent',
        name: 'Analyze scope',
        x: 0,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: find refactor opportunities in {{TARGET_PATH}} honoring {{RISK_THRESHOLD}}.\nConstraints: classify the overall scope; no code changes yet.\nDone when: the plan is ready.\nEnd with a ## SUMMARY and a final line SCOPE=LARGE (risky/broad) or SCOPE=SMALL (safe/local).',
      },
      {
        id: 'cond_scope',
        type: 'condition',
        name: 'Large scope?',
        x: 240,
        y: 0,
        conditionMode: 'outputMatch',
        conditionPattern: 'SCOPE=LARGE',
      },
      {
        id: 'approve',
        type: 'checkpoint',
        name: 'Approve refactor',
        x: 480,
        y: -160,
        message: 'Large refactor scope — review the plan before proceeding.',
      },
      {
        id: 'refactor',
        type: 'agent',
        name: 'Apply refactor',
        x: 720,
        y: 0,
        agent: 'codex',
        _roleName: 'Refactorer',
        retryCount: 1,
        timeout: 600000,
        prompt:
          'Goal: apply the refactor described in context.\nConstraints: behavior-preserving; no API breaks unless the plan says so.\nDone when: applied.\nEnd with a ## SUMMARY (what changed).',
      },
      {
        id: 'run_tests',
        type: 'shell',
        name: 'Run tests',
        x: 960,
        y: 0,
        command: '{{TEST_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'cond_tests',
        type: 'condition',
        name: 'Tests pass?',
        x: 1200,
        y: 0,
        conditionMode: 'exitCode',
      },
      {
        id: 'done_refactor',
        type: 'shell',
        name: 'Refactor complete',
        x: 1440,
        y: 0,
        command: 'true',
      },
      {
        id: 'escape_refactor',
        type: 'checkpoint',
        name: 'Did not converge',
        x: 1200,
        y: 200,
        message: 'Refactor still failing tests after 3 attempts — review.',
      },
    ],
    edges: [
      { id: 'rc_e1', fromNodeId: 'analyze', toNodeId: 'cond_scope' },
      { id: 'rc_e2', fromNodeId: 'cond_scope', toNodeId: 'approve', branch: 'true' },
      { id: 'rc_e3', fromNodeId: 'cond_scope', toNodeId: 'refactor', branch: 'false' },
      { id: 'rc_e4', fromNodeId: 'approve', toNodeId: 'refactor' },
      { id: 'rc_e5', fromNodeId: 'refactor', toNodeId: 'run_tests' },
      { id: 'rc_e6', fromNodeId: 'run_tests', toNodeId: 'cond_tests' },
      { id: 'rc_e7', fromNodeId: 'cond_tests', toNodeId: 'done_refactor', branch: 'true' },
      {
        id: 'rc_e8',
        fromNodeId: 'cond_tests',
        toNodeId: 'refactor',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 3,
      },
      { id: 'rc_e9', fromNodeId: 'cond_tests', toNodeId: 'escape_refactor', branch: 'false' },
    ],
    variables: [
      { name: 'TARGET_PATH', label: 'Target path', type: 'path', required: true },
      {
        name: 'RISK_THRESHOLD',
        label: 'Risk threshold',
        type: 'choice',
        choices: ['conservative', 'moderate', 'aggressive'],
        default: 'moderate',
      },
      { name: 'TEST_CMD', label: 'Test command', type: 'string', default: 'npm test' },
    ],
  },
  {
    id: 'seed-wf-release-readiness',
    name: 'Release Readiness',
    description:
      'Runs four release gates (lint, test, build, audit) concurrently, synthesizes a pass/fail report, then gates publishing behind both the verdict and a human checkpoint.',
    nodes: [
      {
        id: 'start',
        type: 'shell',
        name: 'Start',
        x: 0,
        y: 0,
        command: 'git status --short',
        continueOnError: true,
        timeout: 60000,
      },
      {
        id: 'lint',
        type: 'shell',
        name: 'Lint',
        x: 240,
        y: -330,
        command: '{{LINT_CMD}}',
        continueOnError: true,
        timeout: 300000,
      },
      {
        id: 'test',
        type: 'shell',
        name: 'Test',
        x: 240,
        y: -110,
        command: '{{TEST_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'build',
        type: 'shell',
        name: 'Build',
        x: 240,
        y: 110,
        command: '{{BUILD_CMD}}',
        continueOnError: true,
        timeout: 600000,
      },
      {
        id: 'audit',
        type: 'shell',
        name: 'Audit',
        x: 240,
        y: 330,
        command: '{{AUDIT_CMD}}',
        continueOnError: true,
        timeout: 300000,
      },
      {
        id: 'synthesize',
        type: 'agent',
        name: 'Synthesize report',
        x: 480,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: read the four gate outputs from context (labelled by node: lint, test, build, audit) and report pass/fail per gate.\nConstraints: judge each gate from its output; do not re-run anything.\nDone when: reported.\nEnd with a ## SUMMARY and a final line RELEASE_READY=YES (all gates clean) or RELEASE_READY=NO: <which failed>.',
      },
      {
        id: 'cond_ready',
        type: 'condition',
        name: 'Release ready?',
        x: 720,
        y: 0,
        conditionMode: 'outputMatch',
        conditionPattern: 'RELEASE_READY=YES',
      },
      {
        id: 'publish_gate',
        type: 'checkpoint',
        name: 'Publish',
        x: 960,
        y: -110,
        message: 'All gates green. Publish {{VERSION}}?',
      },
      {
        id: 'dist_tag',
        type: 'shell',
        name: 'Publish release',
        x: 1200,
        y: -110,
        command: '{{PUBLISH_CMD}}',
        timeout: 600000,
      },
      {
        id: 'report_only',
        type: 'shell',
        name: 'Report only',
        x: 960,
        y: 110,
        command: 'true',
      },
    ],
    edges: [
      { id: 'rr_e1', fromNodeId: 'start', toNodeId: 'lint' },
      { id: 'rr_e2', fromNodeId: 'start', toNodeId: 'test' },
      { id: 'rr_e3', fromNodeId: 'start', toNodeId: 'build' },
      { id: 'rr_e4', fromNodeId: 'start', toNodeId: 'audit' },
      { id: 'rr_e5', fromNodeId: 'lint', toNodeId: 'synthesize' },
      { id: 'rr_e6', fromNodeId: 'test', toNodeId: 'synthesize' },
      { id: 'rr_e7', fromNodeId: 'build', toNodeId: 'synthesize' },
      { id: 'rr_e8', fromNodeId: 'audit', toNodeId: 'synthesize' },
      { id: 'rr_e9', fromNodeId: 'synthesize', toNodeId: 'cond_ready' },
      { id: 'rr_e10', fromNodeId: 'cond_ready', toNodeId: 'publish_gate', branch: 'true' },
      { id: 'rr_e11', fromNodeId: 'cond_ready', toNodeId: 'report_only', branch: 'false' },
      { id: 'rr_e12', fromNodeId: 'publish_gate', toNodeId: 'dist_tag' },
    ],
    variables: [
      { name: 'VERSION', label: 'Version', type: 'string' },
      { name: 'LINT_CMD', label: 'Lint command', type: 'string', default: 'npm run lint' },
      { name: 'TEST_CMD', label: 'Test command', type: 'string', default: 'npm test' },
      { name: 'BUILD_CMD', label: 'Build command', type: 'string', default: 'npm run build' },
      {
        name: 'AUDIT_CMD',
        label: 'Audit command',
        type: 'string',
        default: 'npm audit --audit-level=high',
      },
      { name: 'PUBLISH_CMD', label: 'Publish command', type: 'string', default: 'npm run dist' },
    ],
  },
  {
    id: 'seed-wf-design-verify',
    name: 'Cross-Agent Design Verify',
    description:
      'Adversarial generate↔critic loop across two models: Claude drafts a design spec, Codex critiques it, looping until the verdict is READY (or escaping after four rounds) before writing the final spec.',
    nodes: [
      {
        id: 'start',
        type: 'shell',
        name: 'Start',
        x: 0,
        y: 0,
        command: 'true',
        continueOnError: true,
        timeout: 30000,
      },
      {
        id: 'draft',
        type: 'agent',
        name: 'Draft spec',
        x: 240,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: draft (or revise, using the critique in context) a design spec for {{TOPIC}}.\nConstraints: on a revise pass, address every point the critique raised.\nDone when: the spec covers architecture, components, and edge cases.\nEnd with a ## SUMMARY: the key decisions and spec body, ≤ 3 KB.',
      },
      {
        id: 'critique',
        type: 'agent',
        name: 'Critique spec',
        x: 480,
        y: 0,
        agent: 'codex',
        _roleName: 'Adversarial Reviewer',
        retryCount: 1,
        timeout: 300000,
        prompt:
          'Goal: adversarially review the spec in context — find gaps, contradictions, unhandled cases, and hidden assumptions.\nConstraints: assume the spec is flawed until proven otherwise; be specific.\nDone when: reviewed.\nEnd with a ## SUMMARY whose final line is exactly VERDICT=READY or VERDICT=REVISE, plus reasons.',
      },
      {
        id: 'cond_ready',
        type: 'condition',
        name: 'Verdict ready?',
        x: 720,
        y: 0,
        conditionMode: 'outputMatch',
        conditionPattern: 'VERDICT=READY',
      },
      {
        id: 'write_spec',
        type: 'agent',
        name: 'Write final spec',
        x: 960,
        y: 0,
        agent: 'claude-code',
        timeout: 300000,
        prompt:
          'Goal: write the final approved spec (from context) to {{SPEC_PATH}}.\nConstraints: include only the agreed design; no unresolved critique items.\nDone when: the file is written.',
      },
      {
        id: 'escape_design',
        type: 'checkpoint',
        name: 'Did not converge',
        x: 720,
        y: 200,
        message: 'Spec not READY after 4 critique rounds — review draft.',
      },
    ],
    edges: [
      { id: 'dv_e1', fromNodeId: 'start', toNodeId: 'draft' },
      { id: 'dv_e2', fromNodeId: 'draft', toNodeId: 'critique' },
      { id: 'dv_e3', fromNodeId: 'critique', toNodeId: 'cond_ready' },
      { id: 'dv_e4', fromNodeId: 'cond_ready', toNodeId: 'write_spec', branch: 'true' },
      {
        id: 'dv_e5',
        fromNodeId: 'cond_ready',
        toNodeId: 'draft',
        branch: 'false',
        edgeType: 'loop',
        maxIterations: 4,
      },
      { id: 'dv_e6', fromNodeId: 'cond_ready', toNodeId: 'escape_design', branch: 'false' },
    ],
    variables: [
      { name: 'TOPIC', label: 'Design topic', type: 'text', required: true },
      { name: 'SPEC_PATH', label: 'Spec output path', type: 'path' },
    ],
  },
]
